import type {
  Product,
  Rfq,
  RfqLine,
  RfqSupplierResponse,
  AiModel,
  AiTask,
  Company,
  Contact,
  CustomerInquiry,
  Deal,
  PoItem,
  PurchaseOrder,
  Supplier,
  SupplierProfile,
  SupplierQuote,
  SupplierRelationshipEvent,
} from "./supabase";

// Mock data — used when Supabase is not configured (no ERP/DB integration yet).
// Shapes follow ETA-Blueprint ENT-SUPPLIER-001 (Supplier Entity).
//
// DEMO DATA DISCLAIMER: all company, supplier, and contact names below are fictional.
// They do not represent, and are not modeled on, any real organization or person.
// Any resemblance to an actual company is coincidental. See AppLayout's demo banner
// for the user-facing disclaimer (ETA-AUDIT-001, finding 5.1).

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-000125",
    supplier_code: "SUP-000125",
    name: "Damavand Steel Works",
    category: "Manufacturer",
    email: "sales@damavandsteel.com",
    phone: "+98 31 5555 0125",
    website: "damavandsteel.com",
    country: "Iran",
    rating: 4,
    status: "active",
    payment_terms: "Net 30",
    created_at: "2025-11-02T09:00:00Z",
    lifecycle_status: "Active",
    classification: "Strategic",
    certifications: ["ISO 9001", "ISO 14001"],
    compliance_status: "compliant",
    risk_level: "low",
  },
  {
    id: "sup-000148",
    supplier_code: "SUP-000148",
    name: "Zagros Steel Trading",
    category: "Trading Company",
    email: "export@zagrossteeltrading.com",
    phone: "+98 31 5232 1000",
    website: "zagrossteeltrading.com",
    country: "Iran",
    rating: 5,
    status: "active",
    payment_terms: "Net 45",
    created_at: "2025-09-18T09:00:00Z",
    lifecycle_status: "Active",
    classification: "Strategic",
    certifications: ["ISO 9001", "ISO 45001"],
    compliance_status: "compliant",
    risk_level: "low",
  },
  {
    id: "sup-000162",
    supplier_code: "SUP-000162",
    name: "Simorgh Products Co.",
    category: "Distributor",
    email: "info@simorghproducts.com",
    phone: "+98 21 8877 4400",
    website: "simorghproducts.com",
    country: "Iran",
    rating: 3,
    status: "active",
    payment_terms: "Net 30",
    created_at: "2025-12-01T09:00:00Z",
    lifecycle_status: "Approved",
    classification: "Preferred",
    certifications: ["ISO 9001"],
    compliance_status: "compliant",
    risk_level: "medium",
  },
  {
    id: "sup-000174",
    supplier_code: "SUP-000174",
    name: "Alborz Hot Rolling Mills",
    category: "Manufacturer",
    email: "sales@alborzrolling.com",
    phone: "+98 23 3345 6789",
    website: "alborzrolling.com",
    country: "Iran",
    rating: 4,
    status: "active",
    payment_terms: "Net 60",
    created_at: "2025-10-05T09:00:00Z",
    lifecycle_status: "Active",
    classification: "Preferred",
    certifications: ["ISO 9001", "ISO 14001", "OHSAS 18001"],
    compliance_status: "compliant",
    risk_level: "low",
  },
  {
    id: "sup-000189",
    supplier_code: "SUP-000189",
    name: "Cyrus Steel Partners",
    category: "OEM",
    email: "b2b@cyrussteel.com",
    phone: "+98 31 3399 2211",
    website: "cyrussteel.com",
    country: "Iran",
    rating: 3,
    status: "pending",
    payment_terms: "Net 30",
    created_at: "2026-01-14T09:00:00Z",
    lifecycle_status: "Under Review",
    classification: "Conditional",
    certifications: [],
    compliance_status: "under_review",
    risk_level: "medium",
  },
  {
    id: "sup-000203",
    supplier_code: "SUP-000203",
    name: "Elburz Logistics & Freight",
    category: "Logistics Provider",
    email: "ops@elburzlogistics.com",
    phone: "+98 21 4433 8800",
    website: "elburzlogistics.com",
    country: "UAE",
    rating: 4,
    status: "active",
    payment_terms: "Net 15",
    created_at: "2025-08-22T09:00:00Z",
    lifecycle_status: "Active",
    classification: "Approved",
    certifications: ["ISO 28000"],
    compliance_status: "compliant",
    risk_level: "low",
  },
  {
    id: "sup-000217",
    supplier_code: "SUP-000217",
    name: "Meridian EPC Group",
    category: "EPC Contractor",
    email: "contracts@meridianepc.com",
    phone: "+98 21 8899 0011",
    website: "meridianepc.com",
    country: "Iran",
    rating: 2,
    status: "inactive",
    payment_terms: "Net 90",
    created_at: "2025-06-10T09:00:00Z",
    lifecycle_status: "Suspended",
    classification: "Conditional",
    certifications: ["ISO 9001"],
    compliance_status: "non_compliant",
    risk_level: "high",
  },
  {
    id: "sup-000231",
    supplier_code: "SUP-000231",
    name: "Compass Consulting Group",
    category: "Consultant",
    email: "hello@compassconsulting.com",
    phone: "+98 23 3312 7700",
    website: "compassconsulting.com",
    country: "Iran",
    rating: 5,
    status: "active",
    payment_terms: "Net 30",
    created_at: "2025-12-20T09:00:00Z",
    lifecycle_status: "Active",
    classification: "Preferred",
    certifications: ["ISO 9001"],
    compliance_status: "compliant",
    risk_level: "low",
  },
];

export const mockSupplierRelationshipEvents: Record<string, SupplierRelationshipEvent[]> = {
  "sup-000125": [
    {
      id: "evt-1",
      supplier_id: "sup-000125",
      date: "2025-11-02T09:00:00Z",
      type: "onboarded",
      title: "Supplier onboarded",
      description: "Master data record created and approved by Procurement.",
    },
    {
      id: "evt-2",
      supplier_id: "sup-000125",
      date: "2026-01-15T09:00:00Z",
      type: "certification",
      title: "ISO 14001 certification verified",
      description: "Compliance team confirmed current environmental management certification.",
    },
    {
      id: "evt-3",
      supplier_id: "sup-000125",
      date: "2026-03-10T09:00:00Z",
      type: "order",
      title: "PO-2026-0143 fulfilled on time",
      description: "Hot-rolled coil order delivered 2 days ahead of schedule.",
    },
    {
      id: "evt-4",
      supplier_id: "sup-000125",
      date: "2026-06-01T09:00:00Z",
      type: "review",
      title: "Quarterly performance review",
      description: "Rated 4/5 — strong on-time delivery, minor documentation delays.",
    },
  ],
  "sup-000189": [
    {
      id: "evt-5",
      supplier_id: "sup-000189",
      date: "2026-01-14T09:00:00Z",
      type: "onboarded",
      title: "Supplier submitted for review",
      description: "Awaiting compliance and certification documents.",
    },
    {
      id: "evt-6",
      supplier_id: "sup-000189",
      date: "2026-02-20T09:00:00Z",
      type: "issue",
      title: "Missing compliance documentation",
      description: "Tax registration certificate requested, not yet received.",
    },
  ],
  "sup-000217": [
    {
      id: "evt-7",
      supplier_id: "sup-000217",
      date: "2025-06-10T09:00:00Z",
      type: "onboarded",
      title: "Supplier onboarded",
      description: "Approved for EPC contract work under Sprint 1 pilot.",
    },
    {
      id: "evt-8",
      supplier_id: "sup-000217",
      date: "2025-12-05T09:00:00Z",
      type: "issue",
      title: "Delivery delay on PO-2025-0987",
      description: "Project milestone missed by 3 weeks, root cause under investigation.",
    },
    {
      id: "evt-9",
      supplier_id: "sup-000217",
      date: "2026-02-01T09:00:00Z",
      type: "review",
      title: "Supplier suspended",
      description: "Suspended pending resolution of compliance non-conformance.",
    },
  ],
};

export const mockCompanies: Company[] = [
  {
    id: "co-1",
    name: "Simorgh Holding",
    industry: "Steel Trading",
    website: "simorghholding.com",
    email: "info@simorghholding.com",
    phone: "+98 21 8877 4400",
    status: "active",
    employees: 320,
    revenue: 42_000_000,
    created_at: "2025-09-01T09:00:00Z",
    updated_at: "2026-06-01T09:00:00Z",
  },
  {
    id: "co-2",
    name: "Cyrus Industrial Group",
    industry: "Manufacturing",
    website: "cyrusgroup.com",
    email: "contact@cyrusgroup.com",
    phone: "+98 31 3399 2211",
    status: "prospect",
    employees: 180,
    revenue: 15_500_000,
    created_at: "2025-11-20T09:00:00Z",
    updated_at: "2026-05-15T09:00:00Z",
  },
  {
    id: "co-3",
    name: "Alborz Rolling Partners",
    industry: "Metals",
    website: "alborzrolling.com",
    email: "sales@alborzrolling.com",
    phone: "+98 23 3345 6789",
    status: "active",
    employees: 540,
    revenue: 68_000_000,
    created_at: "2025-07-11T09:00:00Z",
    updated_at: "2026-06-10T09:00:00Z",
  },
];

export const mockDeals: Deal[] = [
  { id: "d-1", company_id: "co-1", contact_id: null, title: "Q3 Coil Supply Agreement", value: 1_250_000, currency: "USD", stage: "negotiation", probability: 70, expected_close: "2026-09-01", created_at: "2026-06-01T09:00:00Z" },
  { id: "d-2", company_id: "co-2", contact_id: null, title: "Structural Steel Framework Deal", value: 480_000, currency: "USD", stage: "proposal", probability: 45, expected_close: "2026-08-15", created_at: "2026-05-20T09:00:00Z" },
  { id: "d-3", company_id: "co-3", contact_id: null, title: "Annual Rebar Contract Renewal", value: 2_100_000, currency: "USD", stage: "won", probability: 100, expected_close: "2026-06-01", created_at: "2026-04-01T09:00:00Z" },
  { id: "d-4", company_id: "co-1", contact_id: null, title: "Export Logistics Partnership", value: 340_000, currency: "USD", stage: "qualified", probability: 30, expected_close: "2026-10-01", created_at: "2026-06-15T09:00:00Z" },
  { id: "d-5", company_id: "co-2", contact_id: null, title: "New Vendor Onboarding Pilot", value: 95_000, currency: "USD", stage: "lead", probability: 15, expected_close: "2026-11-01", created_at: "2026-06-20T09:00:00Z" },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  { id: "po-1", po_number: "PO-2026-0143", supplier_id: "sup-000125", status: "received", total: 184_500, currency: "USD", order_date: "2026-03-01", expected_delivery: "2026-03-10", created_at: "2026-03-01T09:00:00Z" },
  { id: "po-2", po_number: "PO-2026-0158", supplier_id: "sup-000148", status: "shipped", total: 320_000, currency: "USD", order_date: "2026-05-10", expected_delivery: "2026-06-05", created_at: "2026-05-10T09:00:00Z" },
  { id: "po-3", po_number: "PO-2026-0161", supplier_id: "sup-000174", status: "approved", total: 96_200, currency: "USD", order_date: "2026-06-01", expected_delivery: "2026-06-25", created_at: "2026-06-01T09:00:00Z" },
  { id: "po-4", po_number: "PO-2026-0165", supplier_id: "sup-000203", status: "submitted", total: 41_000, currency: "USD", order_date: "2026-06-18", expected_delivery: "2026-07-02", created_at: "2026-06-18T09:00:00Z" },
  { id: "po-5", po_number: "PO-2026-0170", supplier_id: "sup-000217", status: "draft", total: 15_800, currency: "USD", order_date: "2026-07-01", expected_delivery: null, created_at: "2026-07-01T09:00:00Z" },
];

export const mockAiTasks: AiTask[] = [
  { id: "ai-1", model_id: null, task_type: "supplier_scoring", status: "completed", input_summary: "Score SUP-000125 on delivery reliability", output_summary: "Score: 4.2/5", created_at: "2026-07-01T09:00:00Z", completed_at: "2026-07-01T09:05:00Z" },
  { id: "ai-2", model_id: null, task_type: "price_analysis", status: "running", input_summary: "Compare rebar pricing across active suppliers", output_summary: null, created_at: "2026-07-03T09:00:00Z", completed_at: null },
  { id: "ai-3", model_id: null, task_type: "risk_assessment", status: "pending", input_summary: "Assess SUP-000217 compliance risk", output_summary: null, created_at: "2026-07-03T10:00:00Z", completed_at: null },
];

export const mockContacts: Contact[] = [
  { id: "ct-1", company_id: "co-1", first_name: "Reza", last_name: "Hosseini", email: "r.hosseini@simorghholding.com", phone: "+98 21 8877 4401", title: "Procurement Director", status: "active", created_at: "2025-09-05T09:00:00Z" },
  { id: "ct-2", company_id: "co-1", first_name: "Sara", last_name: "Amini", email: "s.amini@simorghholding.com", phone: "+98 21 8877 4402", title: "Supply Chain Manager", status: "active", created_at: "2025-10-12T09:00:00Z" },
  { id: "ct-3", company_id: "co-2", first_name: "Kaveh", last_name: "Moradi", email: "k.moradi@cyrusgroup.com", phone: "+98 31 3399 2212", title: "Operations Lead", status: "active", created_at: "2025-11-25T09:00:00Z" },
  { id: "ct-4", company_id: "co-3", first_name: "Nazanin", last_name: "Farhadi", email: "n.farhadi@alborzrolling.com", phone: "+98 23 3345 6790", title: "VP Procurement", status: "active", created_at: "2025-07-15T09:00:00Z" },
  { id: "ct-5", company_id: "co-3", first_name: "Omid", last_name: "Rostami", email: "o.rostami@alborzrolling.com", phone: null, title: "Buyer", status: "inactive", created_at: "2025-08-01T09:00:00Z" },
];

export const mockPoItems: Record<string, PoItem[]> = {
  "po-1": [
    { id: "poi-1", po_id: "po-1", description: "Hot-rolled steel coil, 3mm", quantity: 40, unit: "ton", unit_price: 3800, total: 152_000, created_at: "2026-03-01T09:00:00Z" },
    { id: "poi-2", po_id: "po-1", description: "Freight & inspection", quantity: 1, unit: "lot", unit_price: 32_500, total: 32_500, created_at: "2026-03-01T09:00:00Z" },
  ],
  "po-2": [
    { id: "poi-3", po_id: "po-2", description: "Rebar 16mm grade 60", quantity: 80, unit: "ton", unit_price: 4000, total: 320_000, created_at: "2026-05-10T09:00:00Z" },
  ],
};

export const mockSupplierProfiles: SupplierProfile[] = [
  { id: "sp-1", supplier_id: "sup-000125", portal_status: "active", onboarding_step: 5, documents_submitted: true, last_login: "2026-07-02T14:00:00Z", created_at: "2025-11-02T09:00:00Z" },
  { id: "sp-2", supplier_id: "sup-000148", portal_status: "active", onboarding_step: 5, documents_submitted: true, last_login: "2026-07-03T09:30:00Z", created_at: "2025-09-18T09:00:00Z" },
  { id: "sp-3", supplier_id: "sup-000189", portal_status: "onboarding", onboarding_step: 2, documents_submitted: false, last_login: "2026-06-20T11:00:00Z", created_at: "2026-01-14T09:00:00Z" },
  { id: "sp-4", supplier_id: "sup-000217", portal_status: "suspended", onboarding_step: 4, documents_submitted: true, last_login: "2026-01-10T09:00:00Z", created_at: "2025-06-10T09:00:00Z" },
];

export const mockSupplierQuotes: SupplierQuote[] = [
  { id: "sq-1", supplier_id: "sup-000125", po_id: "po-1", quote_number: "Q-2026-0091", total: 184_500, currency: "USD", status: "accepted", valid_until: "2026-03-15", created_at: "2026-02-20T09:00:00Z" },
  { id: "sq-2", supplier_id: "sup-000148", po_id: "po-2", quote_number: "Q-2026-0104", total: 320_000, currency: "USD", status: "accepted", valid_until: "2026-05-20", created_at: "2026-05-01T09:00:00Z" },
  { id: "sq-3", supplier_id: "sup-000174", po_id: null, quote_number: "Q-2026-0118", total: 96_200, currency: "USD", status: "under_review", valid_until: "2026-07-10", created_at: "2026-06-15T09:00:00Z" },
  { id: "sq-4", supplier_id: "sup-000189", po_id: null, quote_number: "Q-2026-0122", total: 41_500, currency: "USD", status: "submitted", valid_until: "2026-07-20", created_at: "2026-06-25T09:00:00Z" },
];

export const mockAiModels: AiModel[] = [
  { id: "am-1", name: "Supplier Scoring Model", provider: "anthropic", model_type: "classification", status: "active", endpoint: null, api_key_ref: null, created_at: "2026-05-01T09:00:00Z" },
  { id: "am-2", name: "Procurement Assistant", provider: "openai", model_type: "chat", status: "active", endpoint: null, api_key_ref: null, created_at: "2026-04-10T09:00:00Z" },
  { id: "am-3", name: "Document Extraction", provider: "google", model_type: "extraction", status: "training", endpoint: null, api_key_ref: null, created_at: "2026-06-28T09:00:00Z" },
];

// Customer Inquiry / Opportunity — first MVP concept (see src/lib/supabase.ts CustomerInquiry).
// Fictional customers/requests — see the DEMO DATA DISCLAIMER at the top of this file.
export const mockCustomerInquiries: CustomerInquiry[] = [
  { id: "inq-1", inquiry_number: "INQ-2026-0041", company_id: "co-1", customer_name: "Simorgh Holding", industry: "Steel", request_date: "2026-07-28", product_equipment: "Galvanized steel coil", technical_specification: "0.5mm, Z275 coating, 1250mm width", quantity: "60 tons", required_delivery_date: "2026-09-15", status: "new", created_at: "2026-07-28T09:00:00Z" },
  { id: "inq-2", inquiry_number: "INQ-2026-0038", company_id: "co-2", customer_name: "Cyrus Industrial Group", industry: "Oil & Gas", request_date: "2026-07-20", product_equipment: "Centrifugal pump", technical_specification: "API 610, 150 m3/h, carbon steel casing", quantity: "2 units", required_delivery_date: "2026-10-01", status: "technical_review", created_at: "2026-07-20T09:00:00Z" },
  { id: "inq-3", inquiry_number: "INQ-2026-0035", company_id: "co-3", customer_name: "Alborz Rolling Partners", industry: "Steel", request_date: "2026-07-14", product_equipment: "Hot-rolled black sheet", technical_specification: "ST52, 6mm thickness, 2000mm width", quantity: "120 tons", required_delivery_date: "2026-09-01", status: "supplier_search", created_at: "2026-07-14T09:00:00Z" },
  { id: "inq-4", inquiry_number: "INQ-2026-0031", company_id: null, customer_name: "Meridian EPC Group", industry: "Petrochemical", request_date: "2026-07-05", product_equipment: "Control valves package", technical_specification: "On/Off & control valves, ANSI 300#, ESD service", quantity: "18 valves", required_delivery_date: "2026-11-10", status: "quotation_preparation", created_at: "2026-07-05T09:00:00Z" },
  { id: "inq-5", inquiry_number: "INQ-2026-0027", company_id: "co-2", customer_name: "Cyrus Industrial Group", industry: "Industrial Equipment", request_date: "2026-06-22", product_equipment: "Gearbox & motor set", technical_specification: "Helical gear unit, 45kW, IE3 motor", quantity: "4 sets", required_delivery_date: "2026-09-30", status: "customer_offer_sent", created_at: "2026-06-22T09:00:00Z" },
  { id: "inq-6", inquiry_number: "INQ-2026-0022", company_id: "co-1", customer_name: "Simorgh Holding", industry: "Oil & Gas", request_date: "2026-06-10", product_equipment: "Pressure transmitters", technical_specification: "4-20mA HART, SIL2, 316SS wetted parts", quantity: "30 units", required_delivery_date: "2026-08-25", status: "negotiation", created_at: "2026-06-10T09:00:00Z" },
  { id: "inq-7", inquiry_number: "INQ-2026-0015", company_id: "co-3", customer_name: "Alborz Rolling Partners", industry: "Steel", request_date: "2026-05-18", product_equipment: "Stainless steel sheet", technical_specification: "304 grade, 2mm, 2B finish", quantity: "40 tons", required_delivery_date: "2026-07-20", status: "won", created_at: "2026-05-18T09:00:00Z" },
  { id: "inq-8", inquiry_number: "INQ-2026-0009", company_id: null, customer_name: "Compass Consulting Group", industry: "Petrochemical", request_date: "2026-04-30", product_equipment: "Heat exchanger", technical_specification: "Shell & tube, TEMA class R, carbon steel", quantity: "1 unit", required_delivery_date: "2026-07-01", status: "lost", created_at: "2026-04-30T09:00:00Z" },
];

// ---------------------------------------------------------------------------
// Product master data — shapes follow ETA-Blueprint ETA-ENT-PRODUCT-002 (Approved).
// Fictional catalogue entries — see the DEMO DATA DISCLAIMER at the top of this file.
// Manufacturer and supplier names are invented; part numbers are illustrative.
// ---------------------------------------------------------------------------
export const mockProducts: Product[] = [
  {
    id: "prd-000125", product_code: "PRD-000125", sku: "ETA-PMP-CF-150", product_name: "Centrifugal Process Pump, API 610 OH2",
    short_name: "API 610 OH2 Pump", technical_name: "Horizontal overhung centrifugal pump, centerline mounted",
    category: "Pumps", subcategory: "Centrifugal", product_type: "Physical Product", brand: "Nirou Pump Works",
    model: "OH2-150-400", revision: "C", lifecycle_status: "Active", active: true,
    unspsc_code: "40151513", hs_code: "8413.70", industry: "Oil & Gas", criticality: "High",
    strategic_item: true, spare_part: false,
    manufacturer_name: "Nirou Pump Works", manufacturer_part_number: "NPW-OH2-150400", country_of_origin: "Iran",
    warranty_months: 18, lead_time_days: 120, preferred_manufacturer: true,
    description: "Single-stage overhung process pump for hydrocarbon service.",
    technical_description: "API 610 11th ed. OH2 configuration, centerline-mounted casing, mechanical seal per API 682 Plan 11.",
    specification: "Capacity 150 m³/h · Head 210 m · 2950 rpm · Carbon steel casing, 12% Cr impeller",
    technical_standard: "API 610 / API 682", material: "ASTM A216 WCB", grade: "WCB", size: "150 × 400",
    weight: 1180, weight_unit: "kg", uom: "unit", pressure_rating: "ANSI 300#", temperature_rating: "-29 °C to 200 °C",
    supplier_id: "sup-000217", alternate_supplier_ids: ["sup-000162"], supplier_part_number: "MER-P-4471",
    moq: 1, supplier_lead_time: 135, preferred_supplier: true,
    procurement_category: "Rotating Equipment", procurement_method: "Competitive", preferred_incoterm: "CIF",
    payment_term: "30% advance / 70% against B/L", standard_delivery_days: 140,
    standard_cost: 48500, currency: "USD", target_purchase_price: 45000, last_purchase_price: 47200,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: true, availability: "Made to order",
    created_at: "2025-03-11T09:00:00Z", updated_at: "2026-07-02T09:00:00Z",
  },
  {
    id: "prd-000131", product_code: "PRD-000131", sku: "ETA-STL-HR-ST52", product_name: "Hot-Rolled Steel Sheet, ST52-3",
    short_name: "HR Sheet ST52-3", technical_name: "Hot-rolled structural steel plate, normalised",
    category: "Steel Products", subcategory: "Hot-Rolled Sheet", product_type: "Raw Material", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "30264401", hs_code: "7208.51", industry: "Steel", criticality: "Medium",
    strategic_item: true, spare_part: false,
    manufacturer_name: "Alborz Hot Rolling Mills", manufacturer_part_number: "AHR-ST52-6", country_of_origin: "Iran",
    warranty_months: null, lead_time_days: 30, preferred_manufacturer: true,
    description: "Structural-grade hot-rolled sheet for fabrication and pressure applications.",
    technical_description: "Normalised low-alloy structural steel, mill test certificate EN 10204 3.1 supplied per heat.",
    specification: "Thickness 6 mm · Width 2000 mm · Coil or cut-to-length",
    technical_standard: "DIN 17100 / EN 10025 S355J2", material: "Low-alloy structural steel", grade: "ST52-3",
    size: "6 × 2000", weight: 94.2, weight_unit: "kg/m²", uom: "ton", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000174", alternate_supplier_ids: ["sup-000125", "sup-000148"], supplier_part_number: "AHR-6-2000",
    moq: 25, supplier_lead_time: 35, preferred_supplier: true,
    procurement_category: "Steel & Flat Products", procurement_method: "Competitive", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 35,
    standard_cost: 780, currency: "USD", target_purchase_price: 745, last_purchase_price: 762,
    price_valid_until: "2026-09-30",
    export_control: false, sanction_sensitive: false, availability: "Ex-stock / mill schedule",
    created_at: "2025-01-20T09:00:00Z", updated_at: "2026-07-28T09:00:00Z",
  },
  {
    id: "prd-000144", product_code: "PRD-000144", sku: "ETA-STL-GI-Z275", product_name: "Galvanized Steel Coil, Z275",
    short_name: "GI Coil Z275", technical_name: "Hot-dip galvanized cold-rolled coil",
    category: "Steel Products", subcategory: "Galvanized Coil", product_type: "Raw Material", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "30264403", hs_code: "7210.49", industry: "Steel", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Damavand Steel Works", manufacturer_part_number: "DSW-GI-05-1250", country_of_origin: "Iran",
    warranty_months: null, lead_time_days: 28, preferred_manufacturer: false,
    description: "Continuously hot-dip galvanized coil for forming and roll-forming applications.",
    technical_description: "Z275 g/m² total both-side coating mass, regular spangle, chromate passivated, lightly oiled.",
    specification: "Thickness 0.5 mm · Width 1250 mm · Coating Z275 · Coil ID 508 mm",
    technical_standard: "EN 10346 DX51D+Z", material: "Cold-rolled steel, hot-dip galvanized", grade: "DX51D",
    size: "0.5 × 1250", weight: 4.25, weight_unit: "kg/m²", uom: "ton", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000125", alternate_supplier_ids: ["sup-000148"], supplier_part_number: "DSW-Z275-05",
    moq: 20, supplier_lead_time: 30, preferred_supplier: false,
    procurement_category: "Steel & Flat Products", procurement_method: "Competitive", preferred_incoterm: "FOB",
    payment_term: "Net 45", standard_delivery_days: 32,
    standard_cost: 905, currency: "USD", target_purchase_price: 870, last_purchase_price: 889,
    price_valid_until: "2026-10-15",
    export_control: false, sanction_sensitive: false, availability: "Mill schedule",
    created_at: "2025-02-14T09:00:00Z", updated_at: "2026-08-01T09:00:00Z",
  },
  {
    id: "prd-000158", product_code: "PRD-000158", sku: "ETA-VLV-CTL-3IN", product_name: "Globe Control Valve, 3\" ANSI 300#",
    short_name: "Control Valve 3\"", technical_name: "Pneumatic globe-style control valve with positioner",
    category: "Valves", subcategory: "Control Valves", product_type: "Physical Product", brand: "Parsian Valve",
    model: "GCV-300-3", revision: "B", lifecycle_status: "Active", active: true,
    unspsc_code: "40141607", hs_code: "8481.80", industry: "Petrochemical", criticality: "Critical",
    strategic_item: true, spare_part: false,
    manufacturer_name: "Parsian Valve Industries", manufacturer_part_number: "PVI-GCV3-300", country_of_origin: "Iran",
    warranty_months: 24, lead_time_days: 90, preferred_manufacturer: true,
    description: "Cage-guided globe control valve for ESD and modulating service.",
    technical_description: "Pneumatic spring-diaphragm actuator, 4–20 mA smart positioner, Class IV shutoff, SIL2 capable.",
    specification: "Size 3\" · ANSI 300# RF · Cv 110 · Fail-closed action",
    technical_standard: "ANSI/ISA 75.01 / IEC 61508", material: "ASTM A216 WCC body, 316SS trim", grade: "WCC",
    size: "3\"", weight: 96, weight_unit: "kg", uom: "unit", pressure_rating: "ANSI 300#", temperature_rating: "-20 °C to 250 °C",
    supplier_id: "sup-000217", alternate_supplier_ids: [], supplier_part_number: "MER-V-8820",
    moq: 1, supplier_lead_time: 100, preferred_supplier: true,
    procurement_category: "Instrumentation & Valves", procurement_method: "Competitive", preferred_incoterm: "CIP",
    payment_term: "LC at sight", standard_delivery_days: 105,
    standard_cost: 14200, currency: "USD", target_purchase_price: 13000, last_purchase_price: 13850,
    price_valid_until: "2026-11-30",
    export_control: true, sanction_sensitive: true, availability: "Made to order",
    created_at: "2025-05-02T09:00:00Z", updated_at: "2026-06-19T09:00:00Z",
  },
  {
    id: "prd-000163", product_code: "PRD-000163", sku: "ETA-MTR-IE3-45", product_name: "Three-Phase Induction Motor, 45 kW IE3",
    short_name: "Motor 45 kW IE3", technical_name: "TEFC squirrel-cage induction motor, premium efficiency",
    category: "Electric Motors", subcategory: "LV Motors", product_type: "Physical Product", brand: "Kavir Electric",
    model: "KE-225M-4", revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "26101101", hs_code: "8501.53", industry: "Industrial Equipment", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Kavir Electric Machines", manufacturer_part_number: "KEM-225M4-45", country_of_origin: "Iran",
    warranty_months: 24, lead_time_days: 45, preferred_manufacturer: false,
    description: "Premium-efficiency LV motor for pump, fan and gearbox drives.",
    technical_description: "TEFC IP55, frame 225M, 4-pole, F-class insulation with B-class rise, suitable for VFD operation.",
    specification: "45 kW · 400 V · 50 Hz · 1475 rpm · IE3",
    technical_standard: "IEC 60034-1 / IEC 60034-30-1", material: "Cast iron frame", grade: null, size: "Frame 225M",
    weight: 340, weight_unit: "kg", uom: "unit", pressure_rating: null, temperature_rating: "-15 °C to 40 °C ambient",
    supplier_id: "sup-000162", alternate_supplier_ids: ["sup-000217"], supplier_part_number: "SIM-M-2251",
    moq: 1, supplier_lead_time: 50, preferred_supplier: true,
    procurement_category: "Electrical Equipment", procurement_method: "Competitive", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 55,
    standard_cost: 6400, currency: "USD", target_purchase_price: 5900, last_purchase_price: 6150,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: false, availability: "Ex-stock",
    created_at: "2025-04-08T09:00:00Z", updated_at: "2026-05-30T09:00:00Z",
  },
  {
    id: "prd-000171", product_code: "PRD-000171", sku: "ETA-GBX-HEL-45", product_name: "Helical Gear Unit, 45 kW",
    short_name: "Helical Gearbox 45 kW", technical_name: "Three-stage helical gear reducer, foot mounted",
    category: "Gearboxes", subcategory: "Helical", product_type: "Physical Product", brand: "Kavir Electric",
    model: "KG-3H-45", revision: "A", lifecycle_status: "Approved", active: true,
    unspsc_code: "27112800", hs_code: "8483.40", industry: "Industrial Equipment", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Kavir Electric Machines", manufacturer_part_number: "KEM-3H45-25", country_of_origin: "Iran",
    warranty_months: 24, lead_time_days: 60, preferred_manufacturer: false,
    description: "Industrial helical reducer matched to the 45 kW IE3 motor for conveyor and mixer drives.",
    technical_description: "Case-hardened ground helical gearing, service factor 1.6, oil-bath lubrication.",
    specification: "Ratio 25:1 · Output torque 2 750 Nm · Foot mounted · Solid output shaft",
    technical_standard: "AGMA 6010 / ISO 6336", material: "Cast iron housing, 18CrNiMo7-6 gearing", grade: null,
    size: "Size 140", weight: 285, weight_unit: "kg", uom: "unit", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000162", alternate_supplier_ids: [], supplier_part_number: "SIM-G-1408",
    moq: 1, supplier_lead_time: 65, preferred_supplier: true,
    procurement_category: "Rotating Equipment", procurement_method: "Competitive", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 70,
    standard_cost: 9800, currency: "USD", target_purchase_price: 9000, last_purchase_price: null,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: false, availability: "Made to order",
    created_at: "2026-02-17T09:00:00Z", updated_at: "2026-07-11T09:00:00Z",
  },
  {
    id: "prd-000182", product_code: "PRD-000182", sku: "ETA-INS-PT-HART", product_name: "Pressure Transmitter, 4–20 mA HART",
    short_name: "Pressure Transmitter", technical_name: "Gauge pressure transmitter, SIL2 certified",
    category: "Instruments", subcategory: "Pressure", product_type: "Physical Product", brand: "Parsian Valve",
    model: "PT-2600", revision: "D", lifecycle_status: "Active", active: true,
    unspsc_code: "41111904", hs_code: "9026.20", industry: "Oil & Gas", criticality: "High",
    strategic_item: false, spare_part: true,
    manufacturer_name: "Parsian Valve Industries", manufacturer_part_number: "PVI-PT2600-S", country_of_origin: "Iran",
    warranty_months: 24, lead_time_days: 35, preferred_manufacturer: true,
    description: "Smart gauge-pressure transmitter for process measurement and safety loops.",
    technical_description: "316L SS wetted parts, ±0.075% accuracy, HART 7, SIL2 per IEC 61508, Ex d IIC T6.",
    specification: "Range 0–40 bar g · Output 4–20 mA HART · 1/2\" NPT process connection",
    technical_standard: "IEC 61508 / IEC 60079", material: "316L stainless steel", grade: "316L", size: "1/2\" NPT",
    weight: 2.4, weight_unit: "kg", uom: "unit", pressure_rating: "40 bar g", temperature_rating: "-40 °C to 85 °C",
    supplier_id: "sup-000217", alternate_supplier_ids: ["sup-000162"], supplier_part_number: "MER-I-3312",
    moq: 5, supplier_lead_time: 40, preferred_supplier: true,
    procurement_category: "Instrumentation & Valves", procurement_method: "Competitive", preferred_incoterm: "CIP",
    payment_term: "Net 45", standard_delivery_days: 45,
    standard_cost: 1150, currency: "USD", target_purchase_price: 1050, last_purchase_price: 1095,
    price_valid_until: "2026-10-31",
    export_control: true, sanction_sensitive: true, availability: "Ex-stock",
    created_at: "2025-06-25T09:00:00Z", updated_at: "2026-06-10T09:00:00Z",
  },
  {
    id: "prd-000195", product_code: "PRD-000195", sku: "ETA-STL-SS-304", product_name: "Stainless Steel Sheet, 304 2B",
    short_name: "SS Sheet 304", technical_name: "Cold-rolled austenitic stainless sheet, 2B finish",
    category: "Steel Products", subcategory: "Stainless Sheet", product_type: "Raw Material", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "30264405", hs_code: "7219.34", industry: "Steel", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Zagros Steel Trading", manufacturer_part_number: "ZST-304-2B-2", country_of_origin: "Iran",
    warranty_months: null, lead_time_days: 40, preferred_manufacturer: false,
    description: "General-purpose austenitic stainless sheet for process and food-grade fabrication.",
    technical_description: "Cold-rolled, annealed and pickled, 2B mill finish, EN 10204 3.1 certificate per heat.",
    specification: "Thickness 2 mm · Width 1500 mm · Finish 2B",
    technical_standard: "ASTM A240 / EN 10088-2", material: "Austenitic stainless steel", grade: "AISI 304",
    size: "2 × 1500", weight: 15.9, weight_unit: "kg/m²", uom: "ton", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000148", alternate_supplier_ids: ["sup-000125"], supplier_part_number: "ZST-3042B",
    moq: 5, supplier_lead_time: 45, preferred_supplier: false,
    procurement_category: "Steel & Flat Products", procurement_method: "Competitive", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 48,
    standard_cost: 2640, currency: "USD", target_purchase_price: 2480, last_purchase_price: 2575,
    price_valid_until: "2026-09-15",
    export_control: false, sanction_sensitive: false, availability: "Ex-stock",
    created_at: "2025-07-19T09:00:00Z", updated_at: "2026-05-18T09:00:00Z",
  },
  {
    id: "prd-000204", product_code: "PRD-000204", sku: "ETA-HEX-ST-R", product_name: "Shell & Tube Heat Exchanger, TEMA R",
    short_name: "Heat Exchanger TEMA R", technical_name: "Fixed tubesheet shell-and-tube heat exchanger",
    category: "EPC Materials", subcategory: "Static Equipment", product_type: "Fabricated Item", brand: null,
    model: "BEM-600", revision: "A", lifecycle_status: "Procurement Review", active: true,
    unspsc_code: "40101701", hs_code: "8419.50", industry: "Petrochemical", criticality: "High",
    strategic_item: true, spare_part: false,
    manufacturer_name: "Meridian Fabrication", manufacturer_part_number: null, country_of_origin: "Iran",
    warranty_months: 18, lead_time_days: 180, preferred_manufacturer: false,
    description: "Custom-fabricated process heat exchanger, TEMA class R for refinery duty.",
    technical_description: "BEM type, fixed tubesheet, ASME VIII Div.1 U-stamp scope under review; hydro and RT per spec.",
    specification: "Shell 600 mm · 128 tubes × 19 mm OD · Duty 1.8 MW",
    technical_standard: "TEMA R / ASME VIII Div.1", material: "Carbon steel shell, 316L tubes", grade: "SA-516 Gr.70",
    size: "600 mm shell", weight: 4200, weight_unit: "kg", uom: "unit",
    pressure_rating: "Shell 16 barg / Tube 25 barg", temperature_rating: "up to 300 °C",
    supplier_id: "sup-000217", alternate_supplier_ids: [], supplier_part_number: null,
    moq: 1, supplier_lead_time: 195, preferred_supplier: false,
    procurement_category: "Static Equipment", procurement_method: "Competitive", preferred_incoterm: "DAP",
    payment_term: "Milestone-based", standard_delivery_days: 200,
    standard_cost: 128000, currency: "USD", target_purchase_price: 118000, last_purchase_price: null,
    price_valid_until: null,
    export_control: false, sanction_sensitive: false, availability: "Made to order",
    created_at: "2026-04-30T09:00:00Z", updated_at: "2026-08-05T09:00:00Z",
  },
  {
    id: "prd-000211", product_code: "PRD-000211", sku: "ETA-SPR-MSEAL-682", product_name: "Mechanical Seal Cartridge, API 682 Plan 11",
    short_name: "Mechanical Seal", technical_name: "Single cartridge mechanical seal, Category 2 Type A",
    category: "Spare Parts", subcategory: "Sealing", product_type: "Spare Part", brand: "Nirou Pump Works",
    model: "MS-682-A65", revision: "B", lifecycle_status: "Active", active: true,
    unspsc_code: "31163000", hs_code: "8484.20", industry: "Oil & Gas", criticality: "Critical",
    strategic_item: false, spare_part: true,
    manufacturer_name: "Nirou Pump Works", manufacturer_part_number: "NPW-MS682-65", country_of_origin: "Iran",
    warranty_months: 12, lead_time_days: 60, preferred_manufacturer: true,
    description: "Critical spare for the API 610 OH2 pump population.",
    technical_description: "Silicon-carbide vs. carbon faces, FKM elastomers, 316SS metallurgy, Plan 11 flush.",
    specification: "Shaft 65 mm · Single cartridge · API 682 Cat.2 Type A",
    technical_standard: "API 682 4th ed.", material: "SiC / carbon / 316SS", grade: null, size: "65 mm",
    weight: 6.8, weight_unit: "kg", uom: "unit", pressure_rating: "25 barg", temperature_rating: "-29 °C to 200 °C",
    supplier_id: "sup-000217", alternate_supplier_ids: ["sup-000162"], supplier_part_number: "MER-S-9014",
    moq: 2, supplier_lead_time: 65, preferred_supplier: true,
    procurement_category: "Rotating Equipment", procurement_method: "Framework", preferred_incoterm: "CIP",
    payment_term: "Net 30", standard_delivery_days: 70,
    standard_cost: 3850, currency: "USD", target_purchase_price: 3500, last_purchase_price: 3720,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: true, availability: "Made to order",
    created_at: "2025-09-12T09:00:00Z", updated_at: "2026-07-22T09:00:00Z",
  },
  {
    id: "prd-000220", product_code: "PRD-000220", sku: "ETA-CMP-SCR-160", product_name: "Rotary Screw Air Compressor, 160 kW",
    short_name: "Screw Compressor 160 kW", technical_name: "Oil-injected rotary screw compressor package",
    category: "Compressors", subcategory: "Rotary Screw", product_type: "Physical Product", brand: "Kavir Electric",
    model: "KC-160-8", revision: "A", lifecycle_status: "Engineering Review", active: true,
    unspsc_code: "40151604", hs_code: "8414.80", industry: "Industrial Equipment", criticality: "High",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Kavir Electric Machines", manufacturer_part_number: "KEM-KC160-8", country_of_origin: "Iran",
    warranty_months: 24, lead_time_days: 110, preferred_manufacturer: false,
    description: "Packaged plant-air compressor with integrated dryer and receiver.",
    technical_description: "Oil-injected twin-screw airend, VFD drive, integrated refrigerant dryer — engineering review of noise and footprint pending.",
    specification: "160 kW · 27 m³/min FAD · 8 barg · Air-cooled",
    technical_standard: "ISO 1217 / ISO 8573-1 Class 1.4.1", material: null, grade: null, size: "160 kW package",
    weight: 2650, weight_unit: "kg", uom: "unit", pressure_rating: "8 barg", temperature_rating: "5 °C to 45 °C ambient",
    supplier_id: "sup-000162", alternate_supplier_ids: [], supplier_part_number: "SIM-C-1608",
    moq: 1, supplier_lead_time: 120, preferred_supplier: false,
    procurement_category: "Rotating Equipment", procurement_method: "Competitive", preferred_incoterm: "DAP",
    payment_term: "40% advance / 60% on delivery", standard_delivery_days: 125,
    standard_cost: 96000, currency: "USD", target_purchase_price: 88000, last_purchase_price: null,
    price_valid_until: null,
    export_control: false, sanction_sensitive: false, availability: "Made to order",
    created_at: "2026-06-05T09:00:00Z", updated_at: "2026-08-08T09:00:00Z",
  },
  {
    id: "prd-000228", product_code: "PRD-000228", sku: "ETA-PIP-SMLS-6", product_name: "Seamless Carbon Steel Pipe, 6\" Sch 40",
    short_name: "Seamless Pipe 6\"", technical_name: "Hot-finished seamless line pipe",
    category: "Pipes", subcategory: "Seamless", product_type: "Raw Material", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "40174900", hs_code: "7304.19", industry: "Oil & Gas", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: "Damavand Steel Works", manufacturer_part_number: "DSW-SMLS-6-40", country_of_origin: "Iran",
    warranty_months: null, lead_time_days: 50, preferred_manufacturer: false,
    description: "Seamless carbon steel pipe for process piping and utility lines.",
    technical_description: "Hot-finished seamless, bevelled ends, mill test certificate EN 10204 3.1.",
    specification: "NPS 6\" · Sch 40 · 6 m random length",
    technical_standard: "ASTM A106 Gr.B / ASME B36.10", material: "Carbon steel", grade: "A106 Gr.B",
    size: "6\" Sch 40", weight: 28.3, weight_unit: "kg/m", uom: "m", pressure_rating: "ANSI 300#", temperature_rating: "up to 425 °C",
    supplier_id: "sup-000125", alternate_supplier_ids: ["sup-000148"], supplier_part_number: "DSW-P-640",
    moq: 60, supplier_lead_time: 55, preferred_supplier: false,
    procurement_category: "Piping & Fittings", procurement_method: "Competitive", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 58,
    standard_cost: 46, currency: "USD", target_purchase_price: 42, last_purchase_price: 44,
    price_valid_until: "2026-10-31",
    export_control: false, sanction_sensitive: false, availability: "Ex-stock",
    created_at: "2025-10-03T09:00:00Z", updated_at: "2026-04-27T09:00:00Z",
  },
  {
    id: "prd-000239", product_code: "PRD-000239", sku: "ETA-FLG-WN-6", product_name: "Weld Neck Flange, 6\" ANSI 300# RF",
    short_name: "WN Flange 6\"", technical_name: "Forged weld-neck flange, raised face",
    category: "Flanges", subcategory: "Weld Neck", product_type: "Physical Product", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "40183100", hs_code: "7307.91", industry: "Oil & Gas", criticality: "Low",
    strategic_item: false, spare_part: true,
    manufacturer_name: "Damavand Steel Works", manufacturer_part_number: "DSW-WN6-300", country_of_origin: "Iran",
    warranty_months: null, lead_time_days: 25, preferred_manufacturer: false,
    description: "Forged flange for 6\" Sch 40 process piping.",
    technical_description: "Forged carbon steel, raised face 125–250 AARH serrated finish, bore matched to Sch 40.",
    specification: "NPS 6\" · ANSI 300# · RF · Bore Sch 40",
    technical_standard: "ASME B16.5 / ASTM A105", material: "Forged carbon steel", grade: "A105N",
    size: "6\" 300#", weight: 18.5, weight_unit: "kg", uom: "unit", pressure_rating: "ANSI 300#", temperature_rating: "up to 425 °C",
    supplier_id: "sup-000125", alternate_supplier_ids: ["sup-000148"], supplier_part_number: "DSW-F-6300",
    moq: 10, supplier_lead_time: 28, preferred_supplier: false,
    procurement_category: "Piping & Fittings", procurement_method: "Framework", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 30,
    standard_cost: 118, currency: "USD", target_purchase_price: 105, last_purchase_price: 112,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: false, availability: "Ex-stock",
    created_at: "2025-11-08T09:00:00Z", updated_at: "2026-03-14T09:00:00Z",
  },
  {
    id: "prd-000247", product_code: "PRD-000247", sku: "ETA-SRV-INSP-TPI", product_name: "Third-Party Inspection Service",
    short_name: "TPI Service", technical_name: "Vendor surveillance and pre-shipment inspection",
    category: "Services", subcategory: "Inspection", product_type: "Service", brand: null,
    model: null, revision: "A", lifecycle_status: "Active", active: true,
    unspsc_code: "81101701", hs_code: null, industry: "Industrial Equipment", criticality: "Medium",
    strategic_item: false, spare_part: false,
    manufacturer_name: null, manufacturer_part_number: null, country_of_origin: null,
    warranty_months: null, lead_time_days: 7, preferred_manufacturer: false,
    description: "Independent inspection at supplier works, witness of tests and release-note issuance.",
    technical_description: "Scope per ITP: material verification, dimensional check, witness of hydro/performance test, final release note.",
    specification: "Per inspection visit · Man-day basis · Report within 3 working days",
    technical_standard: "ISO/IEC 17020", material: null, grade: null, size: null,
    weight: null, weight_unit: null, uom: "man-day", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000231", alternate_supplier_ids: [], supplier_part_number: "CCG-TPI-01",
    moq: 1, supplier_lead_time: 7, preferred_supplier: true,
    procurement_category: "Services", procurement_method: "Framework", preferred_incoterm: null,
    payment_term: "Net 30", standard_delivery_days: 7,
    standard_cost: 480, currency: "USD", target_purchase_price: 450, last_purchase_price: 465,
    price_valid_until: "2026-12-31",
    export_control: false, sanction_sensitive: false, availability: "On request",
    created_at: "2025-12-01T09:00:00Z", updated_at: "2026-02-20T09:00:00Z",
  },
  {
    id: "prd-000253", product_code: "PRD-000253", sku: "ETA-BRG-SPH-224", product_name: "Spherical Roller Bearing, 22224",
    short_name: "Bearing 22224", technical_name: "Double-row spherical roller bearing, cylindrical bore",
    category: "Bearings", subcategory: "Roller", product_type: "Spare Part", brand: null,
    model: "22224 E", revision: "A", lifecycle_status: "Obsolete", active: false,
    unspsc_code: "31171504", hs_code: "8482.30", industry: "Industrial Equipment", criticality: "Low",
    strategic_item: false, spare_part: true,
    manufacturer_name: "Kavir Electric Machines", manufacturer_part_number: "KEM-22224E", country_of_origin: "Iran",
    warranty_months: 12, lead_time_days: 30, preferred_manufacturer: false,
    description: "Superseded by PRD-000255 following the 2026 gearbox redesign.",
    technical_description: "Retained for historical traceability on the installed base — not available for new projects (BR-012).",
    specification: "Bore 120 mm · OD 215 mm · Width 58 mm",
    technical_standard: "ISO 15:2017", material: "Bearing steel", grade: "100Cr6", size: "120 × 215 × 58",
    weight: 10.8, weight_unit: "kg", uom: "unit", pressure_rating: null, temperature_rating: null,
    supplier_id: "sup-000162", alternate_supplier_ids: [], supplier_part_number: "SIM-B-22224",
    moq: 4, supplier_lead_time: 35, preferred_supplier: false,
    procurement_category: "Rotating Equipment", procurement_method: "Framework", preferred_incoterm: "EXW",
    payment_term: "Net 30", standard_delivery_days: 38,
    standard_cost: 395, currency: "USD", target_purchase_price: 360, last_purchase_price: 382,
    price_valid_until: "2025-12-31",
    export_control: false, sanction_sensitive: false, availability: "Discontinued",
    created_at: "2024-08-14T09:00:00Z", updated_at: "2026-01-30T09:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// RFQ transactions — shapes follow ETA-Blueprint ETA-ENT-RFQ-002 (Approved);
// statuses follow ETA-ENT-RFQ-001, stages follow ETA-ENT-RFQ-005.
// Fictional customers and suppliers — see the DEMO DATA DISCLAIMER at the top.
// No score, rank or recommendation is stored on any record by design.
// ---------------------------------------------------------------------------
export const mockRfqs: Rfq[] = [
  {
    id: "rfq-000154", rfq_number: "RFQ-2026-000154", customer_rfq_number: "SH-PR-88213", internal_reference: "INQ-2026-0041",
    rfq_type: "Customer RFQ", rfq_status: "Draft", priority: "Normal", revision: 0, active: true,
    company_id: "co-1", customer_name: "Simorgh Holding", end_user: "Simorgh Cold Rolling Plant", epc_contractor: null,
    customer_contact_name: "Reza Hosseini", customer_email: "r.hosseini@simorghholding.com",
    rfq_title: "Galvanized steel coil — Z275, 60 tons", description: "Coil supply for the cold-rolling line re-stock.",
    scope_of_supply: "Supply of galvanized coil, mill test certificates, delivery to Tehran works.",
    industry: "Steel", procurement_owner: "A. Hejazi", engineering_owner: null,
    rfq_date: "2026-07-28", submission_deadline: null, customer_deadline: "2026-08-20T12:00:00Z",
    required_delivery_date: "2026-09-15", expected_award_date: null, valid_until: null,
    engineering_review_status: "not_started", engineering_approval: false, engineering_notes: null, technical_risk_level: "Low",
    invited_supplier_ids: [], supplier_response_count: 0, winning_supplier_id: null,
    incoterm: null, delivery_location: "Tehran", payment_terms: null, currency: "USD",
    validity_period: null, partial_delivery_allowed: true, split_award_allowed: false,
    procurement_category: "Steel & Flat Products", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: false, budget_amount: 58000, buyer: "A. Hejazi",
    compliance_review: false, export_control: false, sanction_screening: false, compliance_status: "not_started",
    created_at: "2026-07-28T09:00:00Z",
  },
  {
    id: "rfq-000151", rfq_number: "RFQ-2026-000151", customer_rfq_number: "CIG-2026-0442", internal_reference: "INQ-2026-0038",
    rfq_type: "Strategic RFQ", rfq_status: "Engineering Review", priority: "High", revision: 0, active: true,
    company_id: "co-2", customer_name: "Cyrus Industrial Group", end_user: "Bandar Refinery Unit 4", epc_contractor: "Meridian EPC Group",
    customer_contact_name: "Kaveh Moradi", customer_email: "k.moradi@cyrusgroup.com",
    rfq_title: "API 610 OH2 process pumps — 2 units", description: "Replacement pumps for crude transfer duty.",
    scope_of_supply: "Two API 610 OH2 pumps with baseplate, coupling, guard, mechanical seals and commissioning spares.",
    industry: "Oil & Gas", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-07-20", submission_deadline: "2026-08-25T12:00:00Z", customer_deadline: "2026-09-05T12:00:00Z",
    required_delivery_date: "2026-10-01", expected_award_date: "2026-09-10", valid_until: "2026-10-20",
    engineering_review_status: "in_review", engineering_approval: false,
    engineering_notes: "Datasheet revision B under review — seal plan to be confirmed against site utility.",
    technical_risk_level: "Medium",
    invited_supplier_ids: [], supplier_response_count: 0, winning_supplier_id: null,
    incoterm: "CIF", delivery_location: "Bandar Abbas", payment_terms: "30% advance / 70% against B/L", currency: "USD",
    validity_period: 60, partial_delivery_allowed: false, split_award_allowed: false,
    procurement_category: "Rotating Equipment", strategic_procurement: true, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 105000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: true, compliance_status: "in_review",
    created_at: "2026-07-20T09:00:00Z",
  },
  {
    id: "rfq-000147", rfq_number: "RFQ-2026-000147", customer_rfq_number: "ARP-Q-7714", internal_reference: "INQ-2026-0035",
    rfq_type: "Competitive RFQ", rfq_status: "Procurement Review", priority: "Normal", revision: 1, active: true,
    company_id: "co-3", customer_name: "Alborz Rolling Partners", end_user: "Alborz Rolling Partners", epc_contractor: null,
    customer_contact_name: "Nazanin Farhadi", customer_email: "n.farhadi@alborzrolling.com",
    rfq_title: "Hot-rolled sheet ST52-3 — 120 tons", description: "Structural sheet for the mill extension project.",
    scope_of_supply: "Supply of 120 t hot-rolled sheet, cut to length, EN 10204 3.1 certificates.",
    industry: "Steel", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-07-14", submission_deadline: "2026-08-18T12:00:00Z", customer_deadline: "2026-08-28T12:00:00Z",
    required_delivery_date: "2026-09-01", expected_award_date: "2026-08-22", valid_until: "2026-09-20",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Grade and thickness confirmed against customer drawing rev.2.", technical_risk_level: "Low",
    invited_supplier_ids: ["sup-000174", "sup-000125"], supplier_response_count: 0, winning_supplier_id: null,
    incoterm: "EXW", delivery_location: "Semnan", payment_terms: "Net 30", currency: "USD",
    validity_period: 45, partial_delivery_allowed: true, split_award_allowed: true,
    procurement_category: "Steel & Flat Products", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 96000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: false, compliance_status: "cleared",
    created_at: "2026-07-14T09:00:00Z",
  },
  {
    id: "rfq-000142", rfq_number: "RFQ-2026-000142", customer_rfq_number: "MER-P-2026-118", internal_reference: "INQ-2026-0031",
    rfq_type: "Project RFQ", rfq_status: "Approved", priority: "High", revision: 0, active: true,
    company_id: null, customer_name: "Meridian EPC Group", end_user: "Asaluyeh Petrochemical Complex", epc_contractor: "Meridian EPC Group",
    customer_contact_name: "Farid Ansari", customer_email: "f.ansari@meridianepc.com",
    rfq_title: "Control valves package — 18 valves", description: "ESD and modulating valve package for Unit 2.",
    scope_of_supply: "18 control valves with actuators, positioners, ITP, TPI and site commissioning support.",
    industry: "Petrochemical", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-07-05", submission_deadline: "2026-08-15T12:00:00Z", customer_deadline: "2026-09-01T12:00:00Z",
    required_delivery_date: "2026-11-10", expected_award_date: "2026-08-25", valid_until: "2026-10-05",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "SIL2 certification and ESD fail action confirmed on all tags.", technical_risk_level: "High",
    invited_supplier_ids: ["sup-000217", "sup-000162", "sup-000231"], supplier_response_count: 0, winning_supplier_id: null,
    incoterm: "CIP", delivery_location: "Asaluyeh", payment_terms: "LC at sight", currency: "USD",
    validity_period: 60, partial_delivery_allowed: false, split_award_allowed: false,
    procurement_category: "Instrumentation & Valves", strategic_procurement: true, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 265000, buyer: "A. Hejazi",
    compliance_review: true, export_control: true, sanction_screening: true, compliance_status: "cleared",
    created_at: "2026-07-05T09:00:00Z",
  },
  {
    id: "rfq-000138", rfq_number: "RFQ-2026-000138", customer_rfq_number: "SH-PR-88190", internal_reference: "INQ-2026-0022",
    rfq_type: "Customer RFQ", rfq_status: "Sent", priority: "Normal", revision: 0, active: true,
    company_id: "co-1", customer_name: "Simorgh Holding", end_user: "Simorgh Gas Treatment", epc_contractor: null,
    customer_contact_name: "Sara Amini", customer_email: "s.amini@simorghholding.com",
    rfq_title: "Pressure transmitters — 30 units", description: "SIL2 transmitters for the gas treatment safety loops.",
    scope_of_supply: "30 pressure transmitters, calibration certificates, manifolds and mounting brackets.",
    industry: "Oil & Gas", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-06-10", submission_deadline: "2026-08-16T12:00:00Z", customer_deadline: "2026-08-22T12:00:00Z",
    required_delivery_date: "2026-08-25", expected_award_date: "2026-08-18", valid_until: "2026-09-10",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Range and Ex rating confirmed against loop schedule.", technical_risk_level: "Medium",
    invited_supplier_ids: ["sup-000217", "sup-000162"], supplier_response_count: 1, winning_supplier_id: null,
    incoterm: "CIP", delivery_location: "Tehran", payment_terms: "Net 45", currency: "USD",
    validity_period: 45, partial_delivery_allowed: true, split_award_allowed: false,
    procurement_category: "Instrumentation & Valves", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 42000, buyer: "A. Hejazi",
    compliance_review: true, export_control: true, sanction_screening: true, compliance_status: "cleared",
    created_at: "2026-06-10T09:00:00Z",
  },
  {
    id: "rfq-000133", rfq_number: "RFQ-2026-000133", customer_rfq_number: "CIG-2026-0398", internal_reference: "INQ-2026-0027",
    rfq_type: "Customer RFQ", rfq_status: "Supplier Responding", priority: "Normal", revision: 0, active: true,
    company_id: "co-2", customer_name: "Cyrus Industrial Group", end_user: "Cyrus Conveyor Line 3", epc_contractor: null,
    customer_contact_name: "Kaveh Moradi", customer_email: "k.moradi@cyrusgroup.com",
    rfq_title: "Gearbox and motor sets — 4 sets", description: "Drive packages for the conveyor upgrade.",
    scope_of_supply: "4 helical gear units with matched IE3 motors, base frames and couplings.",
    industry: "Industrial Equipment", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-06-22", submission_deadline: "2026-08-14T12:00:00Z", customer_deadline: "2026-08-30T12:00:00Z",
    required_delivery_date: "2026-09-30", expected_award_date: "2026-08-20", valid_until: "2026-09-25",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Service factor 1.6 and ratio confirmed with the customer's drive calculation.", technical_risk_level: "Low",
    invited_supplier_ids: ["sup-000162", "sup-000217", "sup-000231"], supplier_response_count: 2, winning_supplier_id: null,
    incoterm: "EXW", delivery_location: "Isfahan", payment_terms: "Net 30", currency: "USD",
    validity_period: 45, partial_delivery_allowed: true, split_award_allowed: true,
    procurement_category: "Rotating Equipment", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 72000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: false, compliance_status: "cleared",
    created_at: "2026-06-22T09:00:00Z",
  },
  {
    id: "rfq-000128", rfq_number: "RFQ-2026-000128", customer_rfq_number: "CCG-2026-0071", internal_reference: "INQ-2026-0009",
    rfq_type: "Project RFQ", rfq_status: "Evaluation", priority: "High", revision: 1, active: true,
    company_id: null, customer_name: "Compass Consulting Group", end_user: "Bandar Refinery Unit 2", epc_contractor: "Meridian EPC Group",
    customer_contact_name: "Leila Sadeghi", customer_email: "l.sadeghi@compassconsult.com",
    rfq_title: "Shell & tube heat exchanger — TEMA R", description: "Custom-fabricated exchanger for the crude preheat train.",
    scope_of_supply: "Design, fabrication, testing and delivery of one TEMA R exchanger with ASME documentation.",
    industry: "Petrochemical", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-04-30", submission_deadline: "2026-07-30T12:00:00Z", customer_deadline: "2026-08-25T12:00:00Z",
    required_delivery_date: "2026-12-15", expected_award_date: "2026-08-18", valid_until: "2026-09-30",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Thermal design and TEMA class confirmed. U-stamp scope carried as a commercial option.",
    technical_risk_level: "High",
    invited_supplier_ids: ["sup-000217", "sup-000162", "sup-000231"], supplier_response_count: 3, winning_supplier_id: null,
    incoterm: "DAP", delivery_location: "Bandar Abbas", payment_terms: "Milestone-based", currency: "USD",
    validity_period: 90, partial_delivery_allowed: false, split_award_allowed: false,
    procurement_category: "Static Equipment", strategic_procurement: true, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 140000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: true, compliance_status: "cleared",
    created_at: "2026-04-30T09:00:00Z",
  },
  {
    id: "rfq-000121", rfq_number: "RFQ-2026-000121", customer_rfq_number: "ARP-Q-7688", internal_reference: "INQ-2026-0015",
    rfq_type: "Repeat RFQ", rfq_status: "Awarded", priority: "Normal", revision: 0, active: true,
    company_id: "co-3", customer_name: "Alborz Rolling Partners", end_user: "Alborz Rolling Partners", epc_contractor: null,
    customer_contact_name: "Nazanin Farhadi", customer_email: "n.farhadi@alborzrolling.com",
    rfq_title: "Stainless steel sheet 304 — 40 tons", description: "Repeat order against the 2026 framework.",
    scope_of_supply: "40 t of 2 mm 304 2B sheet with EN 10204 3.1 certificates.",
    industry: "Steel", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-05-18", submission_deadline: "2026-06-10T12:00:00Z", customer_deadline: "2026-06-25T12:00:00Z",
    required_delivery_date: "2026-07-20", expected_award_date: "2026-06-15", valid_until: "2026-07-31",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Identical to the 2025 award specification.", technical_risk_level: "Low",
    invited_supplier_ids: ["sup-000148", "sup-000125", "sup-000174"], supplier_response_count: 3,
    winning_supplier_id: "sup-000148",
    incoterm: "EXW", delivery_location: "Semnan", payment_terms: "Net 30", currency: "USD",
    validity_period: 45, partial_delivery_allowed: true, split_award_allowed: false,
    procurement_category: "Steel & Flat Products", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 108000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: false, compliance_status: "cleared",
    created_at: "2026-05-18T09:00:00Z",
  },
  {
    id: "rfq-000115", rfq_number: "RFQ-2026-000115", customer_rfq_number: "SH-PR-88044", internal_reference: null,
    rfq_type: "Customer RFQ", rfq_status: "Closed", priority: "Low", revision: 0, active: false,
    company_id: "co-1", customer_name: "Simorgh Holding", end_user: "Simorgh Utilities", epc_contractor: null,
    customer_contact_name: "Reza Hosseini", customer_email: "r.hosseini@simorghholding.com",
    rfq_title: "Seamless pipe and flanges — utility line", description: "Piping materials for the utility tie-in.",
    scope_of_supply: "6\" seamless pipe and matching weld-neck flanges with certificates.",
    industry: "Oil & Gas", procurement_owner: "A. Hejazi", engineering_owner: "M. Tabatabai",
    rfq_date: "2026-03-12", submission_deadline: "2026-04-02T12:00:00Z", customer_deadline: "2026-04-15T12:00:00Z",
    required_delivery_date: "2026-05-30", expected_award_date: "2026-04-10", valid_until: "2026-05-15",
    engineering_review_status: "approved", engineering_approval: true,
    engineering_notes: "Closed out — delivery accepted 2026-05-24.", technical_risk_level: "Low",
    invited_supplier_ids: ["sup-000125", "sup-000148"], supplier_response_count: 2, winning_supplier_id: "sup-000125",
    incoterm: "EXW", delivery_location: "Tehran", payment_terms: "Net 30", currency: "USD",
    validity_period: 30, partial_delivery_allowed: true, split_award_allowed: true,
    procurement_category: "Piping & Fittings", strategic_procurement: false, emergency_procurement: false,
    competitive_bidding: true, single_source: false, budget_approved: true, budget_amount: 34000, buyer: "A. Hejazi",
    compliance_review: true, export_control: false, sanction_screening: false, compliance_status: "cleared",
    created_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "rfq-000109", rfq_number: "RFQ-2026-000109", customer_rfq_number: "CIG-2026-0301", internal_reference: null,
    rfq_type: "Emergency RFQ", rfq_status: "Cancelled", priority: "High", revision: 0, active: false,
    company_id: "co-2", customer_name: "Cyrus Industrial Group", end_user: "Cyrus Plant Air System", epc_contractor: null,
    customer_contact_name: "Kaveh Moradi", customer_email: "k.moradi@cyrusgroup.com",
    rfq_title: "Rotary screw air compressor — 160 kW", description: "Cancelled — customer deferred the plant-air upgrade.",
    scope_of_supply: "One 160 kW packaged screw compressor with dryer and receiver.",
    industry: "Industrial Equipment", procurement_owner: "A. Hejazi", engineering_owner: null,
    rfq_date: "2026-02-05", submission_deadline: "2026-02-20T12:00:00Z", customer_deadline: "2026-03-01T12:00:00Z",
    required_delivery_date: "2026-06-30", expected_award_date: null, valid_until: null,
    engineering_review_status: "rejected", engineering_approval: false,
    engineering_notes: "Noise and footprint constraints unresolved before cancellation.", technical_risk_level: "High",
    invited_supplier_ids: ["sup-000162"], supplier_response_count: 0, winning_supplier_id: null,
    incoterm: "DAP", delivery_location: "Isfahan", payment_terms: "40% advance / 60% on delivery", currency: "USD",
    validity_period: 30, partial_delivery_allowed: false, split_award_allowed: false,
    procurement_category: "Rotating Equipment", strategic_procurement: false, emergency_procurement: true,
    competitive_bidding: false, single_source: true, budget_approved: false, budget_amount: 98000, buyer: "A. Hejazi",
    compliance_review: false, export_control: false, sanction_screening: false, compliance_status: "not_started",
    created_at: "2026-02-05T09:00:00Z",
  },
];

export const mockRfqLines: Record<string, RfqLine[]> = {
  "rfq-000154": [
    { id: "rl-154-1", rfq_id: "rfq-000154", line_number: 1, product_id: "prd-000144", product_code: "PRD-000144", product_name: "Galvanized Steel Coil, Z275", quantity: 60, uom: "ton", estimated_budget: 54300, currency: "USD", preferred_manufacturer: "Damavand Steel Works", preferred_supplier_id: "sup-000125", technical_specification: "0.5 mm × 1250 mm, Z275 coating, regular spangle", datasheet_attached: false },
    { id: "rl-154-2", rfq_id: "rfq-000154", line_number: 2, product_id: null, product_code: null, product_name: "Edge protection and packing", quantity: null, uom: null, estimated_budget: null, currency: "USD", preferred_manufacturer: null, preferred_supplier_id: null, technical_specification: null, datasheet_attached: false },
  ],
  "rfq-000151": [
    { id: "rl-151-1", rfq_id: "rfq-000151", line_number: 1, product_id: "prd-000125", product_code: "PRD-000125", product_name: "Centrifugal Process Pump, API 610 OH2", quantity: 2, uom: "unit", estimated_budget: 97000, currency: "USD", preferred_manufacturer: "Nirou Pump Works", preferred_supplier_id: "sup-000217", technical_specification: "150 m³/h @ 210 m, API 610 OH2, seal plan 11", datasheet_attached: true },
    { id: "rl-151-2", rfq_id: "rfq-000151", line_number: 2, product_id: "prd-000211", product_code: "PRD-000211", product_name: "Mechanical Seal Cartridge, API 682 Plan 11", quantity: 2, uom: "unit", estimated_budget: 7700, currency: "USD", preferred_manufacturer: "Nirou Pump Works", preferred_supplier_id: "sup-000217", technical_specification: "65 mm shaft, SiC/carbon faces, FKM elastomers", datasheet_attached: false },
  ],
  "rfq-000147": [
    { id: "rl-147-1", rfq_id: "rfq-000147", line_number: 1, product_id: "prd-000131", product_code: "PRD-000131", product_name: "Hot-Rolled Steel Sheet, ST52-3", quantity: 120, uom: "ton", estimated_budget: 93600, currency: "USD", preferred_manufacturer: "Alborz Hot Rolling Mills", preferred_supplier_id: "sup-000174", technical_specification: "6 mm × 2000 mm, ST52-3, cut to length", datasheet_attached: true },
  ],
  "rfq-000142": [
    { id: "rl-142-1", rfq_id: "rfq-000142", line_number: 1, product_id: "prd-000158", product_code: "PRD-000158", product_name: "Globe Control Valve, 3\" ANSI 300#", quantity: 12, uom: "unit", estimated_budget: 170400, currency: "USD", preferred_manufacturer: "Parsian Valve Industries", preferred_supplier_id: "sup-000217", technical_specification: "3\" ANSI 300# RF, Cv 110, fail-closed, SIL2", datasheet_attached: true },
    { id: "rl-142-2", rfq_id: "rfq-000142", line_number: 2, product_id: "prd-000158", product_code: "PRD-000158", product_name: "Globe Control Valve, 3\" ANSI 300# — ESD service", quantity: 6, uom: "unit", estimated_budget: 88000, currency: "USD", preferred_manufacturer: "Parsian Valve Industries", preferred_supplier_id: "sup-000217", technical_specification: "ESD on/off duty, partial stroke test capable", datasheet_attached: true },
    { id: "rl-142-3", rfq_id: "rfq-000142", line_number: 3, product_id: "prd-000247", product_code: "PRD-000247", product_name: "Third-Party Inspection Service", quantity: 6, uom: "man-day", estimated_budget: 2880, currency: "USD", preferred_manufacturer: null, preferred_supplier_id: "sup-000231", technical_specification: "Witness of FAT and pre-shipment inspection per ITP", datasheet_attached: true },
  ],
  "rfq-000138": [
    { id: "rl-138-1", rfq_id: "rfq-000138", line_number: 1, product_id: "prd-000182", product_code: "PRD-000182", product_name: "Pressure Transmitter, 4–20 mA HART", quantity: 30, uom: "unit", estimated_budget: 34500, currency: "USD", preferred_manufacturer: "Parsian Valve Industries", preferred_supplier_id: "sup-000217", technical_specification: "0–40 barg, SIL2, Ex d IIC T6, 316L wetted parts", datasheet_attached: true },
  ],
  "rfq-000133": [
    { id: "rl-133-1", rfq_id: "rfq-000133", line_number: 1, product_id: "prd-000171", product_code: "PRD-000171", product_name: "Helical Gear Unit, 45 kW", quantity: 4, uom: "unit", estimated_budget: 39200, currency: "USD", preferred_manufacturer: "Kavir Electric Machines", preferred_supplier_id: "sup-000162", technical_specification: "Ratio 25:1, 2 750 Nm, foot mounted, SF 1.6", datasheet_attached: true },
    { id: "rl-133-2", rfq_id: "rfq-000133", line_number: 2, product_id: "prd-000163", product_code: "PRD-000163", product_name: "Three-Phase Induction Motor, 45 kW IE3", quantity: 4, uom: "unit", estimated_budget: 25600, currency: "USD", preferred_manufacturer: "Kavir Electric Machines", preferred_supplier_id: "sup-000162", technical_specification: "45 kW, 400 V, 4-pole, IE3, IP55, VFD-rated", datasheet_attached: true },
  ],
  "rfq-000128": [
    { id: "rl-128-1", rfq_id: "rfq-000128", line_number: 1, product_id: "prd-000204", product_code: "PRD-000204", product_name: "Shell & Tube Heat Exchanger, TEMA R", quantity: 1, uom: "unit", estimated_budget: 128000, currency: "USD", preferred_manufacturer: "Meridian Fabrication", preferred_supplier_id: "sup-000217", technical_specification: "BEM, 600 mm shell, 128 × 19 mm tubes, duty 1.8 MW", datasheet_attached: true },
    { id: "rl-128-2", rfq_id: "rfq-000128", line_number: 2, product_id: "prd-000247", product_code: "PRD-000247", product_name: "Third-Party Inspection Service", quantity: 10, uom: "man-day", estimated_budget: 4800, currency: "USD", preferred_manufacturer: null, preferred_supplier_id: "sup-000231", technical_specification: "Stage inspections per ITP including hydro witness", datasheet_attached: true },
  ],
  "rfq-000121": [
    { id: "rl-121-1", rfq_id: "rfq-000121", line_number: 1, product_id: "prd-000195", product_code: "PRD-000195", product_name: "Stainless Steel Sheet, 304 2B", quantity: 40, uom: "ton", estimated_budget: 105600, currency: "USD", preferred_manufacturer: "Zagros Steel Trading", preferred_supplier_id: "sup-000148", technical_specification: "2 mm × 1500 mm, AISI 304, 2B finish", datasheet_attached: true },
  ],
  "rfq-000115": [
    { id: "rl-115-1", rfq_id: "rfq-000115", line_number: 1, product_id: "prd-000228", product_code: "PRD-000228", product_name: "Seamless Carbon Steel Pipe, 6\" Sch 40", quantity: 600, uom: "m", estimated_budget: 27600, currency: "USD", preferred_manufacturer: "Damavand Steel Works", preferred_supplier_id: "sup-000125", technical_specification: "A106 Gr.B, 6\" Sch 40, 6 m random length", datasheet_attached: true },
    { id: "rl-115-2", rfq_id: "rfq-000115", line_number: 2, product_id: "prd-000239", product_code: "PRD-000239", product_name: "Weld Neck Flange, 6\" ANSI 300# RF", quantity: 48, uom: "unit", estimated_budget: 5664, currency: "USD", preferred_manufacturer: "Damavand Steel Works", preferred_supplier_id: "sup-000125", technical_specification: "A105N, 6\" 300# RF, bore Sch 40", datasheet_attached: true },
  ],
  "rfq-000109": [
    { id: "rl-109-1", rfq_id: "rfq-000109", line_number: 1, product_id: "prd-000220", product_code: "PRD-000220", product_name: "Rotary Screw Air Compressor, 160 kW", quantity: 1, uom: "unit", estimated_budget: 96000, currency: "USD", preferred_manufacturer: "Kavir Electric Machines", preferred_supplier_id: "sup-000162", technical_specification: "160 kW, 27 m³/min FAD @ 8 barg, integrated dryer", datasheet_attached: false },
  ],
};

export const mockRfqResponses: Record<string, RfqSupplierResponse[]> = {
  "rfq-000138": [
    { id: "rr-138-1", rfq_id: "rfq-000138", supplier_id: "sup-000217", supplier_name: "Meridian EPC Group", response_status: "quoted", quote_number: "MER-Q-2026-441", quoted_total: 33450, currency: "USD", delivery_days: 40, payment_terms: "Net 45", incoterm: "CIP", warranty_months: 24, validity_days: 45, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-08-06T10:20:00Z" },
    { id: "rr-138-2", rfq_id: "rfq-000138", supplier_id: "sup-000162", supplier_name: "Simorgh Products Co.", response_status: "responding", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
  ],
  "rfq-000133": [
    { id: "rr-133-1", rfq_id: "rfq-000133", supplier_id: "sup-000162", supplier_name: "Simorgh Products Co.", response_status: "quoted", quote_number: "SIM-Q-4418", quoted_total: 61200, currency: "USD", delivery_days: 65, payment_terms: "Net 30", incoterm: "EXW", warranty_months: 24, validity_days: 45, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-08-04T08:15:00Z" },
    { id: "rr-133-2", rfq_id: "rfq-000133", supplier_id: "sup-000217", supplier_name: "Meridian EPC Group", response_status: "quoted", quote_number: "MER-Q-2026-433", quoted_total: 66800, currency: "USD", delivery_days: 55, payment_terms: "Net 30", incoterm: "EXW", warranty_months: 24, validity_days: 60, technical_compliance: "not_evaluated", deviation_notes: "Alternative gear ratio 22:1 offered in place of 25:1.", submitted_at: "2026-08-07T14:40:00Z" },
    { id: "rr-133-3", rfq_id: "rfq-000133", supplier_id: "sup-000231", supplier_name: "Compass Consulting Group", response_status: "declined", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: "Outside scope of supply.", submitted_at: null },
  ],
  "rfq-000128": [
    { id: "rr-128-1", rfq_id: "rfq-000128", supplier_id: "sup-000217", supplier_name: "Meridian EPC Group", response_status: "quoted", quote_number: "MER-Q-2026-402", quoted_total: 131500, currency: "USD", delivery_days: 195, payment_terms: "Milestone-based", incoterm: "DAP", warranty_months: 18, validity_days: 90, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-07-24T09:30:00Z" },
    { id: "rr-128-2", rfq_id: "rfq-000128", supplier_id: "sup-000162", supplier_name: "Simorgh Products Co.", response_status: "quoted", quote_number: "SIM-Q-4402", quoted_total: 124800, currency: "USD", delivery_days: 215, payment_terms: "Milestone-based", incoterm: "DAP", warranty_months: 12, validity_days: 60, technical_compliance: "deviation", deviation_notes: "ASME U-stamp excluded; offers national code certification instead.", submitted_at: "2026-07-28T11:05:00Z" },
    { id: "rr-128-3", rfq_id: "rfq-000128", supplier_id: "sup-000231", supplier_name: "Compass Consulting Group", response_status: "quoted", quote_number: "CCG-Q-0188", quoted_total: 5100, currency: "USD", delivery_days: 7, payment_terms: "Net 30", incoterm: null, warranty_months: null, validity_days: 60, technical_compliance: "compliant", deviation_notes: "Inspection scope only (line 2).", submitted_at: "2026-07-26T15:50:00Z" },
  ],
  "rfq-000121": [
    { id: "rr-121-1", rfq_id: "rfq-000121", supplier_id: "sup-000148", supplier_name: "Zagros Steel Trading", response_status: "quoted", quote_number: "ZST-Q-9917", quoted_total: 103200, currency: "USD", delivery_days: 45, payment_terms: "Net 30", incoterm: "EXW", warranty_months: null, validity_days: 45, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-06-04T09:00:00Z" },
    { id: "rr-121-2", rfq_id: "rfq-000121", supplier_id: "sup-000125", supplier_name: "Damavand Steel Works", response_status: "quoted", quote_number: "DSW-Q-3341", quoted_total: 107600, currency: "USD", delivery_days: 40, payment_terms: "Net 30", incoterm: "EXW", warranty_months: null, validity_days: 30, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-06-05T13:20:00Z" },
    { id: "rr-121-3", rfq_id: "rfq-000121", supplier_id: "sup-000174", supplier_name: "Alborz Hot Rolling Mills", response_status: "quoted", quote_number: "AHR-Q-1120", quoted_total: 109900, currency: "USD", delivery_days: 55, payment_terms: "Net 45", incoterm: "EXW", warranty_months: null, validity_days: 45, technical_compliance: "deviation", deviation_notes: "2B finish substituted with BA finish.", submitted_at: "2026-06-06T10:10:00Z" },
  ],
  "rfq-000115": [
    { id: "rr-115-1", rfq_id: "rfq-000115", supplier_id: "sup-000125", supplier_name: "Damavand Steel Works", response_status: "quoted", quote_number: "DSW-Q-3218", quoted_total: 32900, currency: "USD", delivery_days: 55, payment_terms: "Net 30", incoterm: "EXW", warranty_months: null, validity_days: 30, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-03-28T09:00:00Z" },
    { id: "rr-115-2", rfq_id: "rfq-000115", supplier_id: "sup-000148", supplier_name: "Zagros Steel Trading", response_status: "quoted", quote_number: "ZST-Q-9840", quoted_total: 34600, currency: "USD", delivery_days: 48, payment_terms: "Net 30", incoterm: "EXW", warranty_months: null, validity_days: 30, technical_compliance: "compliant", deviation_notes: null, submitted_at: "2026-03-30T11:30:00Z" },
  ],
  "rfq-000147": [
    { id: "rr-147-1", rfq_id: "rfq-000147", supplier_id: "sup-000174", supplier_name: "Alborz Hot Rolling Mills", response_status: "invited", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
    { id: "rr-147-2", rfq_id: "rfq-000147", supplier_id: "sup-000125", supplier_name: "Damavand Steel Works", response_status: "invited", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
  ],
  "rfq-000142": [
    { id: "rr-142-1", rfq_id: "rfq-000142", supplier_id: "sup-000217", supplier_name: "Meridian EPC Group", response_status: "invited", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
    { id: "rr-142-2", rfq_id: "rfq-000142", supplier_id: "sup-000162", supplier_name: "Simorgh Products Co.", response_status: "invited", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
    { id: "rr-142-3", rfq_id: "rfq-000142", supplier_id: "sup-000231", supplier_name: "Compass Consulting Group", response_status: "invited", quote_number: null, quoted_total: null, currency: null, delivery_days: null, payment_terms: null, incoterm: null, warranty_months: null, validity_days: null, technical_compliance: "not_evaluated", deviation_notes: null, submitted_at: null },
  ],
};
